version: '3'
services:
  db:
    container_name: postgres_database
    environment:
      - POSTGRES_PASSWORD=123456
    volumes:
      # - postgres-db:/var/lib/postgresql/data Named Volume
      - ./postgres-db:/var/lib/postgresql/data
    image: postgres:15.1
  pyAdmin:
    depends_on:
      - db
    image: dpage/pgadmin4:6.17
    environment:
      - PGADMIN_DEFAULT_PASSWORD=123456
      - PGADMIN_DEFAULT_EMAIL=superman@google.com
    volumes:
      - ./pgadmin4:/var/lib/pgadmin
    ports:
      - 8080:80
# volumes:
#   postgres-db:
#     external: true